export function getEventTypes(_, { forStart = false, forIntermediate = false, forEnd = false } = {}) {
  return [
    {
      name: 'none',
      label: _('None'),
      sprite: 'bpmn-none',
      forStart: true,
      forIntermediate: true,
      forEnd: true,
    },
    {
      name: 'message',
      label: _('Message'),
      sprite: 'bpmn-message',
      forStart: true,
      forIntermediate: true,
      forEnd: true,
    },
    {
      name: 'timer',
      label: _('Timer'),
      sprite: 'bpmn-timer',
      forStart: true,
      forIntermediate: true,
      forEnd: false,
    },
    {
      name: 'signal',
      label: _('Signal'),
      sprite: 'bpmn-signal',
      forStart: true,
      forIntermediate: true,
      forEnd: true,
    },
    {
      name: 'conditional',
      label: _('Conditional'),
      sprite: 'bpmn-conditional',
      forStart: true,
      forIntermediate: true,
      forEnd: false,
    },
    {
      name: 'error',
      label: _('Error'),
      sprite: 'bpmn-error',
      forStart: false,
      forIntermediate: false,
      forEnd: true,
    },
    {
      name: 'cancel',
      label: _('Cancel'),
      sprite: 'bpmn-cancel',
      forStart: false,
      forIntermediate: false,
      forEnd: true,
    },
    {
      name: 'compensation',
      label: _('Compensation'),
      sprite: 'bpmn-compensation',
      forStart: false,
      forIntermediate: true,
      forEnd: true,
    },
    {
      name: 'link',
      label: _('Link'),
      sprite: 'bpmn-link',
      forStart: false,
      forIntermediate: true,
      forEnd: false,
    },
    {
      name: 'multiple',
      label: _('Multiple'),
      sprite: 'bpmn-multiple',
      forStart: true,
      forIntermediate: true,
      forEnd: true,
    },
    {
      name: 'parallel',
      label: _('Parallel'),
      sprite: 'bpmn-parallel',
      forStart: true,
      forIntermediate: true,
      forEnd: false,
    },
  ].filter(t => (forStart && t.forStart) || (forIntermediate && t.forIntermediate) || (forEnd && t.forEnd));
}